export const TAG_LIST = 'tag_list'
export const NEW_ITEM_NEW_USER_LIST = 'new_item_new_user_list'
export const POPULAR_ITEM_LIST = 'popular_item_list'
export const TOPIC_LIST = 'topic_list'
export const CATE_LIST = 'catelist'
export const RECOMMEND_ONE = 'recommend_one'
export const RECOMMEND_THREE = 'recommend_three'
export const TENFIFTEEN = 'tenfifteen'
export const DATAFENLEI = 'datafenlei'
export const COLUMN = 'column'
export const BANNER = 'banner'
export const GET_RECOMMENDTWO = 'get_recommendtwo'
export const ZHEN_THREE = 'zhen_three'
export const ZHEN_ONE = 'zhen_one'
export const ZHEN_TWO = 'zhen_two'
export const TOPIC = 'topic'
export const CATEGORYL1LIST = 'categoryl1list'


